/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uc_appmarket_common_Encoder */

#ifndef _Included_com_appmall_market_common_Encoder
#define _Included_com_appmall_market_common_Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uc_appmarket_common_Encoder
 * Method:    encode
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_appmall_market_common_Encoder_encode
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_uc_appmarket_common_Encoder
 * Method:    decode
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_appmall_market_common_Encoder_decode
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
